### ISSUE TITLE
Inconsistent logical sizes

### ISSUE THREAD

**Issue by DerekJuba-NIST** [zeiss-microscopy/libCZI#13]
I'm having an issue with inconsistent logical sub-block sizes being reported by libCZI.  I was originally having this problem on a tiled, pyramided microscope image that I am unable to share.  However, I have been able to reproduce the problem by loading a non-tiled jpg image into Zen, generating a pyramid, and saving it as czi.

Here is the output I am getting from CZICmd:

Complete list of sub-blocks
---------------------------

#0: T0 M=-2147483648 logical=(0,0,7695,2160) phys.=(285,80) pixeltype=bgr24
#1: T0 M=-2147483648 logical=(0,0,6561,2160) phys.=(729,240) pixeltype=bgr24
#2: T0 M=-2147483648 logical=(6561,0,1125,2160) phys.=(125,240) pixeltype=bgr24
#3: T0 M=-2147483648 logical=(0,0,2187,2160) phys.=(729,720) pixeltype=bgr24
#4: T0 M=-2147483648 logical=(2187,0,2187,2160) phys.=(729,720) pixeltype=bgr24
#5: T0 M=-2147483648 logical=(4374,0,2187,2160) phys.=(729,720) pixeltype=bgr24
#6: T0 M=-2147483648 logical=(6561,0,1119,2160) phys.=(373,720) pixeltype=bgr24
#7: T0 M=-2147483648 logical=(0,0,7680,2160) phys.=(7680,2160) pixeltype=bgr24

Pyramid-Subblock-Statistics
---------------------------

 number of subblocks with scale 1/1: 1
 number of subblocks with scale 1/3: 4
 number of subblocks with scale 1/9: 2
 number of subblocks with scale 1/27: 1

Notice that the non-tiled, scale 1/1 sub-block (#7) has physical and logical size 7680, 2160.  These are the correct dimensions of the image.  However, the scale 1/27 sub-block (#0) has logical size 7695, 2160.  I believe that this should be equal to the actual image size, but it is a little bigger.  The other pyramid levels have the same problem; for example, if you add up the logical widths from the scale 1/9 sub-blocks (#1 and #2), you get 6561+1125=7686, which is also too big.

I'm not sure if this a problem with libCZI or with Zen itself, but perhaps a developer could advise?

I am attaching the example image.
[example.zip](https://github.com/zeiss-microscopy/libCZI/files/1589813/example.zip)

**Comment by sebi06** [comment]
Hi,

i am not a developer, but to me this looks logical. The original 7680 / 17 = 284.444. Therefore the size must be 285 pixel in size. Of course this leads to 285 * 27 = 7695 pixel, which is bigger than the original 7680 pixel.

Did I misunderstand your issue or could you describe in more detail, where this causes problems for you? Beside this comment I will check back with the developer to get his opinion as well.

**Comment by ptahmose** [comment]
As far as I can tell, this is expected behavior. If a pyramid-tile is created for a rectangular area which has a physical width/height not dividable by 3 (in this case), then it is rounded up. This condition applies to all pyramid-levels, and can result in a noticeable discrepancy.
Iirc, libCZI takes all pyramid-levels into account when reporting the size of the document 
It is a matter of definition what the size of the document is - taking only pyramid-layer-0 into account or all layers. Usually, the latter is used.
So... yes, this might be debatable, but it is expected behavior as of today.

**Comment by DerekJuba-NIST** [comment]
Thanks, this makes sense now.
