### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by dimin** [zeiss-microscopy/libCZI#2]
Hi,

I'm super glad to see this library in the wild, thank you! I'm a developer of libbioimage and BisQue and we would like to get a much better support for your format. We do have commercial clients interested in using our code in the commercial setting and I wanted to know who should I talk to about commercial license for using libCZI.

Thank you very much,
Dmitry

**Comment by ptahmose** [comment]
I suggest to use this contact form: https://www.zeiss.com/microscopy/int/service-support/microscopy-contact.html
