### ISSUE TITLE
Multiple-scene overlapped area rendering

### ISSUE THREAD

**Issue by stanleyycho** [zeiss-microscopy/libCZI#25]
Hello, 

I have a question regarding tile accessor to read multiple scene image. I have an image, sorry that I cannot share it. The tiles and scene is arranged as below figure. The red boundary is scene boundary, the blue area are the tiles and the green are tiles within overlapped area of 2 scene.

The issue I have is that `CSingleChannelTileAccessor` can render the green areas with tissue. However; when I use `CSingleChannelPyramidLevelTileAccessor` to render subsampled images. The green areas become background black pixels, which are copied from background of lower right scene. 

I read the source code and, in the end, both classes call `Compositors::ComposeSingleChannelTiles`. I am wondering how it actually works here. How does the 2 methods determine which tile to render and why I got different results using these two classes.

Thank you.

![image](https://user-images.githubusercontent.com/17039384/38508100-193a10a8-3bd3-11e8-9d8b-fcba066bfb9e.png)

**Comment by stanleyycho** [comment]
Thank you for explaining. I want to clarify one thing. Did you mean that when I request image from top pyramid layer, the sub block holds the image, which is composed of blue and red areas without taking into account of the overlapping issue?
Thanks.

**Comment by stanleyycho** [comment]
Thank you for clarification!
Is there any plan to implement the feature in near future?

**Comment by ptahmose** [comment]
Sorry, I suppose the answer is no.
