### ISSUE TITLE
ChannelComposite extraction using CZIcmd yields only half an image

### ISSUE THREAD

**Issue by Jondeen** [zeiss-microscopy/libCZI#26]
I'm trying to extract the label-image into a more generic image format using the code below. An image 
with correct dimensions is subtracted successfully, however half the image (the right-most part) is missing, or specifically, all pixels after pixel column #365 counting from the left is black (except for the blue channel which, curiously, continues for another column).

Am I doing something wrong here or may there be a bug?

```
$ CZIcmd -s CZIFILE.czi -c extractattachment -o tmp_czi_label_extract -e '{"name":"Label"}'
$ CZIcmd -s tmp_czi_label_extract_Label* -c printinformation

SubBlock-Statistics
-------------------

SubBlock-Count: 1

Bounding-Box:
 All:    X=0 Y=0 W=733 H=552
 Layer0: X=0 Y=0 W=733 H=552

M-Index: not valid

Bounds:
 C -> Start=0 Size=1

$ CZIcmd -c ChannelComposite -r 'abs(0,0,733,552)' -s tmp_czi_label_extract_Label* -o $1.label
```

**Comment by stanleyycho** [comment]
It might be related to the bug #20

**Comment by Jondeen** [comment]
That's right. I should have checked this before reporting -- updating to latest source works. Thanks!
