### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by thomasgt** [zeiss-microscopy/libCZI#34]
Hello,

I see that this project is licensed under GPL. Is there an alternate commercial license available for distribution with proprietary software?

Cheers,
Thomas

**Comment by sebi06** [comment]
Hi Thomas,

Thx for your interest in libCZI. In short, yes there is way to use this library in a commercial software. I will get back to you as soon as I am back in my office. Meanwhile it afoul be nice if you could send me more information on what you plan to do to my work address :+1:

sebastian.rhode@zeiss.com

Sebi(from Zeiss)
