### ISSUE TITLE
Axio Scan Z1 support

### ISSUE THREAD

**Issue by Jondeen** [zeiss-microscopy/libCZI#4]
Hi,

Does this library support the CZI-files produced from the Axio Scan Z1?

Thanks,
Jonas Øgaard

**Comment by ptahmose** [comment]
Yes, absolutely.

**Comment by Jondeen** [comment]
I had some issues compiling the command line tool, mostly thanks to limitations of earlier versions of the gcc/g++ compilers and the glibc libraries (building on linux). As far as I can tell, minimum g++-version needs to be 5.x [for a C++11 standard library (requires at least v4.7), but which also supports codecvt](https://stackoverflow.com/questions/15615136/is-codecvt-not-a-std-header), and upon running with a glibc version at 2.12, I'm getting errors complaining about undeclared align_alloc, which is seemingly resolved by using [glibc versions at or beyond 2.17](https://github.com/Microsoft/CNTK/issues/729). Just putting this out there if other people are running into similar issues.

But more importantly, I can't get the binaries to work even when compiled successfully.
Under glibc 2.19, g++ 5.4.1, Ubuntu trusty 14.04:
`$./CZIcmd -c ExtractAttachment -s A2.czi -o test`
`FATAL ERROR: std:exception caught`
` -> std::exception`

Under glibc 2.23, g++ 5.4.0, Ubuntu xenial 16.04 (under WSL):
`$./CZIcmd -c ExtractAttachment -s A2.czi -o test`
(exits normally with no output, but nothing is written to disk)

A bit in the dark about what extra information I can supply to ease debugging, but if anyone has had similar things happen to them any insights would be most welcome.

**Comment by ptahmose** [comment]
Does a simple
`./CZIcmd -c PrintInformation -s A2.czi`
work (and give a reasonable output)?

What does 
`./CZIcmd -c PrintInformation -i AllAttachments -s A2.czi`
give? It should give something like this

```
Complete list of Attachments
----------------------------

index | filetype | GUID                                   | name
------+----------+----------------------------------------+-------------
    0 | CZTIMS   | {D2FD4125-CBF0-4B27-A8F2-643EDC5BAE7B} | TimeStamps
    1 | CZEVL    | {725AE927-5D00-4EBC-BB61-9362207F1B5D} | EventList
    2 | CZI      | {45165480-EEB9-417E-BC72-877E9A37EDAE} | Label
    3 | CZI      | {DD9A366F-4941-45B9-94FD-6043B1B96C16} | SlidePreview
    4 | JPG      | {7B25A072-7E33-4D2B-8921-DE69D09A3127} | Thumbnail
```
...or - if this list is empty, it would mean that there are no attachments in the CZI.

**Comment by Jondeen** [comment]
Yes printing out information works (for the Xenial-build), I forgot to mention this:
```
$ ./CZIcmd -c PrintInformation -i AllAttachments -s ~/A2.czi
Complete list of Attachments
----------------------------

index | filetype | GUID                                   | name
------+----------+----------------------------------------+-------------
    0 | CZEVL    | {3A392950-EFAA-421D-9F54-ED38D3E7D018} | EventList
    1 | CZTIMS   | {EB634EE0-A337-48B5-8AA0-7899518BA310} | TimeStamps
    2 | CZI      | {C9979EE5-37C9-4CB7-AA9D-E8BE5C3E5E51} | Label
    3 | CZI      | {2E455485-F1F0-4121-8BD8-DC71D3FA8B58} | SlidePreview
    4 | JPG      | {23A74294-FAB9-401C-A210-65C1DC6C396B} | Thumbnail
```

So I guess this could maybe indicate issues with libz (?) or libpng. I'm running versions 1.2.8 of libz (same as test build in documentation), but 1.6.20 for libpng (1.2.51 in documentation).

I'll try downgrading to 1.2.x for libpng and see if this helps.

**Comment by Jondeen** [comment]
Seems like running with libpng 1.2.54 had no effect whatsoever. When I have some more time I can try to find a 1.2.51-version if you think it will have any significant impact.

**Comment by ptahmose** [comment]
Well, sorry, I am somewhat at my wits end here. I cannot tell whether the problems are caused by some compilation/version hiccups or if you are stumbling across some code-issues (aka bugs). Libpng is not used in the case of extracting attachments as far as I can tell, so I don't think that this is related. All I can assure you - for me it is working...
I guess you should try other operations and check whether they work. There is also a little test-suite supplied with the sources (../Src/Test/scripts) - however, it is somewhat useless since the CZI-files necessary to run it are not available.
If you have the chance, maybe you want to try a build on Windows with VisualStudio. Other than that, I'd guess it is time to fire up the debugger...

**Comment by Jondeen** [comment]
I'll start trying to figure out the Xenial build first - 

Here extracting attachments fails silently (exits normally), but trying to extract a region fails with the following error:
```
(gdb) run
Starting program: ~/gits/libCZI/Src/CZICmd/CZIcmd -c ChannelComposite -s ~/A2.czi -o test -r rel\(0,0,1024,1024\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__GI__IO_fwrite (buf=0x7ffffffdd990, size=1, count=8, fp=0x0) at iofwrite.c:37
37      iofwrite.c: No such file or directory.
```

And backtrace:
```
(gdb) backtrace
#0  __GI__IO_fwrite (buf=0x7ffffffdd990, size=1, count=8, fp=0x0) at iofwrite.c:37
#1  0x00007ffffecc19f8 in ?? () from /lib/x86_64-linux-gnu/libpng12.so.0
#2  0x00007ffffecbc1a9 in ?? () from /lib/x86_64-linux-gnu/libpng12.so.0
#3  0x00007ffffecc1b37 in png_write_info_before_PLTE () from /lib/x86_64-linux-gnu/libpng12.so.0
#4  0x00007ffffecc1da7 in png_write_info () from /lib/x86_64-linux-gnu/libpng12.so.0
#5  0x000000000050f57f in CSaveData::SavePngTweakLineBeforeWritng(libCZI::IBitmapData*, int, int, std::function<void (unsigned int, void*)>) (
    this=0x7ffffffddcd0, bitmap=0x762f30, bit_depth=8, color_type=2, tweakLine=...) at ~/gits/libCZI/Src/CZICmd/SaveBitmap.cpp:356
#6  0x000000000050f308 in CSaveData::SaveBgr24 (this=0x7ffffffddcd0, bitmap=0x762f30) at ~/gits/libCZI/Src/CZICmd/SaveBitmap.cpp:318
#7  0x000000000050f1c7 in CSaveData::Save (this=0x7ffffffddcd0, bitmap=0x762f30) at ~/gits/libCZI/Src/CZICmd/SaveBitmap.cpp:291
#8  0x00000000004facd5 in CExecuteChannelComposite::execute (options=...) at ~/gits/libCZI/Src/CZICmd/execute.cpp:711
#9  0x00000000004f11a3 in execute (options=...) at ~/gits/libCZI/Src/CZICmd/execute.cpp:1135
#10 0x000000000050ec43 in main (argc=9, _argv=0x7ffffffde278) at ~/gits/libCZI/Src/CZICmd/CZIcmd.cpp:105
```

**Comment by ptahmose** [comment]
Please check if above patch resolves the issue. What seemed to happen (on Linux only) is that the argument passed in with "-o" was misinterpreted, and in effect (with something like '-o test') output-files were attempted to be created in a folder ../test. As a workaround you could try to give an absolute path (for the -o argument).

**Comment by Jondeen** [comment]
That did it! Thanks!

**Comment by zeissmicroscopy** [comment]
Glad to hear that, you are welcome.
