### ISSUE TITLE
memory initialisation in CHeapAllocator::Allocate

### ISSUE THREAD

**Issue by CHILI-GmbH** [zeiss-microscopy/libCZI#40]
CHeapAllocator::Allocate seems no to initialise the allocated memory.

this is visible if more than one pixmap is created from the image data and the second extends beyond the area of a czi file. 

this can be fixes by calling 'memset( pv, 0, size );' bevor the memory is returned from CHeapAllocator::Allocate.

this is not ideal as it incurs overhead for every pixmap. but fixing this only for pixmaps that extend beyond the visible area looks more complicated.

**Comment by ptahmose** [comment]
Well, I'd think that it would be better to do the initialization only in places where it is necessary - so I'd put the clear-operation not into the "CHeapAllocator::Allocate". However - what you describe seems like a bug to me, but I am not sure what the operations are where you ran into this issue. Can you give some more details, or even better - a repro?

**Comment by CHILI-GmbH** [comment]
steps to reproduce:
- create a pixmap with a CreateSingleChannelScalingTileAccessor that is inside the bounding box
- lock, extract data, unlock
- create a second pixmap with the same accessor that is partly outside the bounding box
- lock, extract data, inlock

-> the extracted data that is outside the bounding box will still contain the pixel data from the first pixmap
