### ISSUE TITLE
Missing/White tile on 5x and below resolution

### ISSUE THREAD

**Issue by pranthakur** [zeiss-microscopy/libCZI#63]
I tried to dump czi image on zoom level 0.00390625000 with CZIcmd.exe 
on lower resolution(below 10x ) tiles around scene-1 appearing as white tile. after 10x they are working fine

` CZIcmd.exe --command SingleChannelScalingTileAccessor --plane-coordinate C0 --rect rel(0,0,90000,70000) --source "D:\images\czi\1-1-7A.czi" --output d:\out\czizmd --zoom 0.00390625000 `

**CZIcmd output**
![czizmd](https://user-images.githubusercontent.com/37903704/182349005-1be74362-7bc7-4ff1-889b-18022698aa29.PNG)

**Snapshot from ZEN viewer(Expected output)**
![expectedImage](https://user-images.githubusercontent.com/37903704/182349751-67ef7219-d65e-4260-a4d2-04b624c7d6bf.PNG)

**Comment by zeissmicroscopy** [comment]
Closing. Repo will be archived in favor of https://github.com/ZEISS/libczi. Please re-open if still needed.
